### ISSUE TITLE
Crashing due to an illegal property class value

### ISSUE THREAD

**Issue by Lemmskii** [QuiltServerTools/Interdimensional#13]
java.lang.IllegalArgumentException: Cannot set property class_2754{name=axis, clazz=class net.minecraft.class_2350$class_2351, values=[x, z]} to y on Block{minecraft:nether_portal}, it is not an allowed value

**Comment by vacla** [comment]
Try latest github actions jar

**Comment by Yot360** [comment]
> Try latest github actions jar

Worked thanks
