### ISSUE TITLE
How about an update 1.18?

### ISSUE THREAD

**Issue by Khikki** [QuiltServerTools/Interdimensional#15]
Will you update Interdimensional to the new version? :)

**Comment by Patbox** [comment]
Yes, there is work done on porting it

**Comment by Genau6502** [comment]
Work is already in progress updating to 1.18 - more details are on the discord

**Comment by KlutzyBubbles** [comment]
If there is work on updating to 1.18. Would you be able to keep the issue open until it has been ported?

Monitoring a discord for updates is annoying compared to subscribing to an issue that **should** be updated with the status of the issue

**Comment by Genau6502** [comment]
The porting has been done. You can subscribe to pings on the discord.

**Comment by KlutzyBubbles** [comment]
> The porting has been done. You can subscribe to pings on the discord.

Nice, I cant subscribe to pings on discord (getting a sound notification and a dot is not subscribing). Would have been much easier if the beta was published in the releases or if this issue had a comment saying 'beta here' or something.

**Comment by Genau6502** [comment]
The more comments I get here, the less time I spend working on the mod. There will be a release when it's ready
