### ISSUE TITLE
Error on server start (polymer)

### ISSUE THREAD

**Issue by ShaKabosh** [QuiltServerTools/Interdimensional#17]
Hello, using verson 1.1.1 with fabric loader 0.12.12, I am getting the following error upon starting the server: https://pastebin.com/QuDz5jm2
The issue appears to be around the Polymer library embedded.
Here is my mod list (in case it is a mod incompatability): https://pastebin.com/3caz4inU

UPDATE: It is an incompatability with immersive portals. Removed Immersive Portals, and it worked.

**Comment by PotatoPresident** [comment]
@Patbox

**Comment by Patbox** [comment]
Update bundled polymer
