### ISSUE TITLE
Allow for per-world portal functionality

### ISSUE THREAD

**Issue by BornToDoStuff** [QuiltServerTools/Interdimensional#6]
There is currently functionality being added to allow for custom portals to go to different dimensions, but I think it would also be very valuable to allow for different portal functionality if you are in a different world.
Say there is two overworlds, each with a nether dimension already created for them. I go to Overworld Alpha, and when I go through a netherportal it teleports me to Nether Alpha. I can replicate this in Overworld Gamma and be teleported respectively to Nether Gamma. It is possible this may be as easy as adding a "from" parameter to the portal command to override where the "from world's" portal's go to (depending on how you guys are implementing the portal command).

**Comment by Genau6502** [comment]
The portal command now has the option to specify the source dimension
